import { documentFontFamily, documentLabel, documentLabelLines, documentNames, documentPaymentLabel } from '@/localization/documents'
import { formatDocumentMoney, formatDocumentQuantity, type DocumentViewModel } from '@/lib/invoices/documentViewModel'
import { resolveA4Template } from '@/lib/invoices/a4TemplateRegistry'
import { RiyalSymbol } from '@/components/ui/RiyalSymbol'

export interface A4RenderOptions {
  readonly id?: string
  readonly preview?: boolean
  readonly pdfMode?: boolean
  readonly pageNumbers?: boolean
  readonly qrImageUrl?: string | null
  readonly sampleLabel?: string | null
}

export interface A4DocumentProps { readonly model: DocumentViewModel; readonly options?: A4RenderOptions }

function Money({ value, model }: { value: number; model: DocumentViewModel }) { return <bdi className="a4-money" dir="ltr"><RiyalSymbol /> {formatDocumentMoney(value, model)}</bdi> }
function names(model: DocumentViewModel, en: string | null, ar: string | null) { return documentNames(model.identity.language, en, ar) }
function DateMeta({ model }: { model: DocumentViewModel }) {
  const date = new Intl.DateTimeFormat(model.format.dateLocale, { timeZone: 'Asia/Riyadh', year: 'numeric', month: '2-digit', day: '2-digit' }).format(new Date(model.identity.issueTimestamp))
  const time = new Intl.DateTimeFormat('en-SA', { timeZone: 'Asia/Riyadh', hour: '2-digit', minute: '2-digit', hour12: false }).format(new Date(model.identity.issueTimestamp))
  const credit = model.identity.kind === 'credit_note'
  return <dl className="a4-meta"><div><dt>{documentLabel(model.identity.language, credit ? 'creditNoteNumber' : 'invoiceNumber')}</dt><dd><bdi dir="ltr">{model.identity.number}</bdi></dd></div><div><dt>{documentLabel(model.identity.language, 'date')}</dt><dd><bdi dir="ltr">{date}</bdi></dd></div><div><dt>{documentLabel(model.identity.language, 'time')}</dt><dd><bdi dir="ltr">{time}</bdi></dd></div>{credit && model.compliance.originalDocument.number && <div><dt>{documentLabel(model.identity.language, 'originalInvoice')}</dt><dd><bdi dir="ltr">{model.compliance.originalDocument.number}</bdi></dd></div>}</dl>
}

function Seller({ model }: { model: DocumentViewModel }) {
  const { seller, presentation } = model
  const logo = presentation.logo.previewUrl ?? presentation.logo.assetPath
  return <section className="a4-seller">{presentation.logo.visible && logo && <img className={`a4-logo a4-logo--${presentation.logo.size ?? 'medium'}`} src={logo} alt="" onError={event => { event.currentTarget.style.display = 'none' }} />}{seller.displayHeading && <div className="a4-display-heading" dir="auto">{seller.displayHeading}</div>}{seller.displaySubheading && <div className="a4-display-subheading" dir="auto">{seller.displaySubheading}</div>}{names(model, seller.registeredName, seller.registeredNameAr).map((value, index) => <div className="a4-registered-name" key={`${value}-${index}`} dir="auto">{value}</div>)}{seller.branch.visible && names(model, seller.branch.name, seller.branch.nameAr).map((value, index) => <div className="a4-branch" key={`${value}-${index}`} dir="auto">{value}</div>)}<div>{documentLabel(model.identity.language, 'vatNumber')}: <bdi dir="ltr">{seller.vatNumber}</bdi></div>{seller.registrationNumber && <div>{seller.registrationType ?? 'CR'}: <bdi dir="ltr">{seller.registrationNumber}</bdi></div>}{seller.registeredAddress && <div className="a4-address" dir="auto">{seller.registeredAddress}</div>}{presentation.contact.phoneVisible && presentation.contact.phone && <div>{documentLabel(model.identity.language, 'phone')}: <bdi dir="ltr">{presentation.contact.phone}</bdi></div>}{presentation.contact.websiteVisible && presentation.contact.website && <div><bdi dir="ltr">{presentation.contact.website}</bdi></div>}{presentation.contact.emailVisible && presentation.contact.email && <div><bdi dir="ltr">{presentation.contact.email}</bdi></div>}</section>
}

function Buyer({ model }: { model: DocumentViewModel }) { const { buyer } = model; return <section className="a4-buyer"><div className="a4-section-title">{documentLabel(model.identity.language, 'billTo')}</div>{names(model, buyer.name, buyer.nameAr).map((value, index) => <div className="a4-buyer-name" key={`${value}-${index}`} dir="auto">{value}</div>)}{buyer.vatNumber && <div>{documentLabel(model.identity.language, 'customerVatNumber')}: <bdi dir="ltr">{buyer.vatNumber}</bdi></div>}{buyer.address && <div dir="auto">{buyer.address}</div>}</section> }

function ItemTable({ model }: { model: DocumentViewModel }) { const credit = model.identity.kind === 'credit_note'; return <table className="a4-items"><thead><tr><th>#</th><th>{documentLabel(model.identity.language, 'item')}</th><th>{documentLabel(model.identity.language, 'quantity')}</th><th>{documentLabel(model.identity.language, 'unitPrice')}</th><th>{documentLabel(model.identity.language, 'discount')}</th><th>{documentLabel(model.identity.language, 'taxableAmount')}</th><th>{documentLabel(model.identity.language, 'vatAmount')}</th><th>{documentLabel(model.identity.language, 'totalIncludingVat')}</th></tr></thead><tbody>{model.items.map((item, index) => <tr key={`${item.description}-${index}`}><td>{index + 1}</td><td>{names(model, item.description, item.descriptionAr).map((value, nameIndex) => <div key={`${value}-${nameIndex}`} dir="auto">{value}</div>)}</td><td><bdi dir="ltr">{formatDocumentQuantity(credit && item.creditedQuantity != null ? item.creditedQuantity : item.quantity, model)}</bdi></td><td><Money value={item.unitPrice} model={model} /></td><td>{item.discount > 0 ? <Money value={item.discount} model={model} /> : '—'}</td><td><Money value={item.taxableAmount} model={model} /></td><td><span><bdi dir="ltr">{formatDocumentQuantity(item.vatRate, model)}%</bdi> · <Money value={item.vatAmount} model={model} /></span></td><td><Money value={item.lineTotal} model={model} /></td></tr>)}</tbody></table> }

function Totals({ model }: { model: DocumentViewModel }) { const credit = model.identity.kind === 'credit_note'; return <section className="a4-totals"><div><span>{documentLabel(model.identity.language, 'amountBeforeVat')}</span><Money value={model.totals.subtotal} model={model} /></div>{model.totals.discount > 0 && <div><span>{documentLabel(model.identity.language, 'discount')}</span><Money value={model.totals.discount} model={model} /></div>}<div><span>{documentLabel(model.identity.language, 'taxableAmount')}</span><Money value={model.totals.taxableAmount} model={model} /></div><div><span>{documentLabel(model.identity.language, 'vatAmount')}</span><Money value={model.totals.vat} model={model} /></div><div className="a4-totals__grand"><span>{documentLabel(model.identity.language, credit ? 'creditTotal' : 'totalIncludingVat')}</span><Money value={model.totals.total} model={model} /></div>{!credit && model.totals.paid > 0 && <div><span>{documentLabel(model.identity.language, 'paid')}</span><Money value={model.totals.paid} model={model} /></div>}{credit && model.totals.refunded > 0 && <div><span>{documentLabel(model.identity.language, 'refunded')}</span><Money value={model.totals.refunded} model={model} /></div>}{!credit && model.totals.balance != null && Math.abs(model.totals.balance) > .005 && <div><span>{documentLabel(model.identity.language, 'balance')}</span><Money value={Math.abs(model.totals.balance)} model={model} /></div>}</section> }

function Payment({ model }: { model: DocumentViewModel }) { if (!model.payments.length) return null; const credit = model.identity.kind === 'credit_note'; return <section className="a4-payment"><div className="a4-section-title">{documentLabel(model.identity.language, credit ? 'refundIssued' : 'paymentMethod')}</div>{model.payments.map((payment, index) => <div key={`${payment.method}-${index}`}><span>{documentPaymentLabel(model.identity.language, payment.method)}</span><Money value={payment.amount} model={model} />{payment.cashTendered != null && <span>{documentLabel(model.identity.language, 'received')}: <Money value={payment.cashTendered} model={model} /></span>}{model.presentation.thermal.showCashChange && (payment.change ?? 0) > 0 && <span>{documentLabel(model.identity.language, 'change')}: <Money value={payment.change ?? 0} model={model} /></span>}</div>)}</section> }

function Footer({ model, options }: { model: DocumentViewModel; options: A4RenderOptions }) { const footer = [model.presentation.footer.thankYouVisible ? model.presentation.footer.thankYou : null, model.presentation.footer.footerVisible ? model.presentation.footer.footer : null, model.presentation.footer.refundVisible ? model.presentation.footer.refund : null].filter(Boolean); const qr = options.qrImageUrl; return <footer className="a4-footer"><div className="a4-qr">{qr ? <img src={qr} alt={documentLabel(model.identity.language, 'qrCode')} /> : <div className="a4-qr-placeholder">{documentLabel(model.identity.language, 'qrCode')}</div>}<small>{documentLabel(model.identity.language, 'scanToVerify')}</small></div><div className="a4-footer-copy">{footer.map((line, index) => <div key={`${line}-${index}`} dir="auto">{line}</div>)}{model.identity.legacy && <small className="a4-legacy-warning" dir="auto">{documentLabel(model.identity.language, 'legacyBestEffort')}</small>}<small>{documentLabel(model.identity.language, model.identity.kind === 'credit_note' ? 'computerGeneratedCreditNote' : 'computerGeneratedInvoice')}</small></div>{options.pageNumbers && <span className="a4-page-number" />}</footer> }

function SharedA4Layout({ model, options, template }: { model: DocumentViewModel; options: A4RenderOptions; template: 'classic' | 'modern_split' | 'minimal_professional' }) { const credit = model.identity.kind === 'credit_note'; const style = resolveA4Template(model).headerStyle; const title = credit ? (model.identity.invoiceType === 'standard' ? 'taxCreditNote' : 'simplifiedTaxCreditNote') : (model.identity.invoiceType === 'standard' ? 'standardTaxInvoice' : 'simplifiedTaxInvoice'); return <article className={`a4-document a4-document--${template} a4-header--${style}`} dir={model.identity.direction} lang={model.identity.language === 'both' ? undefined : model.identity.language}>{options.sampleLabel && <div className="a4-sample">{options.sampleLabel}</div>}<header className="a4-header"><Seller model={model} /><section className="a4-document-title">{documentLabelLines(model.identity.language, title).map((line, index) => <div key={`${line}-${index}`} className={index === 0 ? 'a4-document-title__main' : 'a4-document-title__sub'} dir="auto">{line}</div>)}<DateMeta model={model} /></section></header><Buyer model={model} />{credit && <section className="a4-credit"><strong>{documentLabel(model.identity.language, 'creditNoteReference')}</strong>{model.compliance.originalDocument.number && <span>{documentLabel(model.identity.language, 'originalInvoice')}: <bdi dir="ltr">{model.compliance.originalDocument.number}</bdi></span>}{model.compliance.creditReason && <span>{documentLabel(model.identity.language, 'reason')}: <span dir="auto">{model.compliance.creditReason}</span></span>}</section>}<ItemTable model={model} /><div className="a4-lower"><Payment model={model} /><Totals model={model} /></div><Footer model={model} options={options} /></article> }

function ClassicV1(props: { model: DocumentViewModel; options: A4RenderOptions }) { return <SharedA4Layout {...props} template="classic" /> }
function ModernSplitV1(props: { model: DocumentViewModel; options: A4RenderOptions }) { return <SharedA4Layout {...props} template="modern_split" /> }
function MinimalProfessionalV1(props: { model: DocumentViewModel; options: A4RenderOptions }) { return <SharedA4Layout {...props} template="minimal_professional" /> }

export default function A4Document({ model, options = {} }: A4DocumentProps) { const resolved = resolveA4Template(model); const Template = resolved.renderer === 'modern_split_v1' ? ModernSplitV1 : resolved.renderer === 'minimal_professional_v1' ? MinimalProfessionalV1 : ClassicV1; const target = options.pdfMode ? 'pdf' : options.preview ? 'preview' : 'print'; return <div id={options.id ?? 'a4-document'} className={`a4-document-frame ${options.preview ? '' : 'a4-document-frame--print-only'}`} data-render-target={target} data-template-requested={`${resolved.requestedId}@${resolved.requestedVersion}`} data-template-resolved={`${resolved.resolvedId}@${resolved.resolvedVersion}`} style={{ fontFamily: documentFontFamily(model.identity.language) }}><Template model={model} options={options} /></div> }
