import type { CSSProperties, ReactNode } from 'react'
import { documentFontFamily, documentLabel, documentLabelLines, documentNames, documentPaymentLabel } from '@/localization/documents'
import { formatDocumentMoney, formatDocumentQuantity, type DocumentViewModel } from '@/lib/invoices/documentViewModel'
import { resolveA4Template } from '@/lib/invoices/a4TemplateRegistry'
import { RiyalSymbol } from '@/components/ui/RiyalSymbol'
import { buildVisibleTotals } from '@/lib/invoices/visibleTotals'
import { resolveInvoiceLogoUrl } from '@/lib/invoices/runtimePresentation'

export interface A4RenderOptions {
  readonly id?: string
  readonly preview?: boolean
  readonly pdfMode?: boolean
  readonly pageNumbers?: boolean
  readonly qrImageUrl?: string | null
  readonly sampleLabel?: string | null
  readonly nonFiscalDemo?: boolean
}

export interface A4DocumentProps { readonly model: DocumentViewModel; readonly options?: A4RenderOptions }

function Money({ value, model }: { value: number; model: DocumentViewModel }) { return <bdi className="a4-money" dir="ltr"><RiyalSymbol /> {formatDocumentMoney(value, model)}</bdi> }
function names(model: DocumentViewModel, en: string | null, ar: string | null) { return documentNames(model.identity.language, en, ar) }
function QuantityCell({ model, item, quantity }: { model: DocumentViewModel; item: DocumentViewModel['items'][number]; quantity: number }) { return <><bdi dir="ltr">{formatDocumentQuantity(quantity, model)}</bdi>{names(model, item.unitName, item.unitNameAr).map((value, index) => <div key={`${value}-${index}`} dir="auto">{value}</div>)}</> }
function DateMeta({ model }: { model: DocumentViewModel }) {
  const date = new Intl.DateTimeFormat(model.format.dateLocale, { timeZone: 'Asia/Riyadh', year: 'numeric', month: '2-digit', day: '2-digit' }).format(new Date(model.identity.issueTimestamp))
  const time = new Intl.DateTimeFormat('en-SA', { timeZone: 'Asia/Riyadh', hour: '2-digit', minute: '2-digit', hour12: false }).format(new Date(model.identity.issueTimestamp))
  const supplyDate = model.identity.supplyDate ? new Intl.DateTimeFormat(model.format.dateLocale, { timeZone: 'Asia/Riyadh', year: 'numeric', month: '2-digit', day: '2-digit' }).format(new Date(model.identity.supplyDate)) : null
  const supplyDiffers = supplyDate && supplyDate !== date
  const credit = model.identity.kind === 'credit_note'
  const debit = model.identity.kind === 'debit_note'
  return <dl className="a4-meta">
    <div><dt>{documentLabel(model.identity.language, credit ? 'creditNoteNumber' : debit ? 'debitNoteNumber' : 'invoiceNumber')}</dt><dd><bdi dir="ltr">{model.identity.number}</bdi></dd></div>
    <div><dt>{documentLabel(model.identity.language, 'date')}</dt><dd><bdi dir="ltr">{date}</bdi></dd></div>
    <div><dt>{documentLabel(model.identity.language, 'time')}</dt><dd><bdi dir="ltr">{time}</bdi></dd></div>
    {supplyDiffers && <div><dt>{documentLabel(model.identity.language, 'supplyDate')}</dt><dd><bdi dir="ltr">{supplyDate}</bdi></dd></div>}
    {(credit || debit) && model.compliance.originalDocument.number && <div><dt>{documentLabel(model.identity.language, 'originalInvoice')}</dt><dd><bdi dir="ltr">{model.compliance.originalDocument.number}</bdi></dd></div>}
  </dl>
}

function Seller({ model }: { model: DocumentViewModel }) {
  const { seller, presentation } = model
  const logo = presentation.logo.previewUrl ?? presentation.logo.assetPath
  const presentationAddress = presentation.contact.address
  return <section className="a4-seller">{presentation.logo.visible && logo && <img className={`a4-logo a4-logo--${presentation.logo.size ?? 'medium'}`} src={logo} alt="" onError={event => { event.currentTarget.style.display = 'none' }} />}{seller.displayHeading && <div className="a4-display-heading" dir="auto">{seller.displayHeading}</div>}{seller.displaySubheading && <div className="a4-display-subheading" dir="auto">{seller.displaySubheading}</div>}{seller.company.visible && names(model, seller.registeredName, seller.registeredNameAr).map((value, index) => <div className="a4-registered-name" key={`${value}-${index}`} dir="auto">{value}</div>)}{seller.branch.visible && names(model, seller.branch.name, seller.branch.nameAr).map((value, index) => <div className="a4-branch" key={`${value}-${index}`} dir="auto">{value}</div>)}<section className="a4-legal-seller"><div className="a4-section-title">{documentLabel(model.identity.language, 'seller')}</div>{names(model, seller.registeredName, seller.registeredNameAr).map((value, index) => <div className="a4-legal-seller__name" key={`${value}-${index}`} dir="auto">{value}</div>)}{seller.registeredAddress && <div className="a4-address" dir="auto">{seller.registeredAddress}</div>}{seller.vatNumber && <div>{documentLabel(model.identity.language, 'vatNumber')}: <bdi dir="ltr">{seller.vatNumber}</bdi></div>}{seller.registrationNumber && <div>{seller.registrationType === 'CR' ? documentLabel(model.identity.language, 'crNumber') : seller.registrationType ?? documentLabel(model.identity.language, 'identifier')}: <bdi dir="ltr">{seller.registrationNumber}</bdi></div>}</section>{presentation.contact.addressVisible && presentationAddress && presentationAddress !== seller.registeredAddress && <div className="a4-address a4-address--presentation" dir="auto">{presentationAddress}</div>}{presentation.contact.phoneVisible && presentation.contact.phone && <div>{documentLabel(model.identity.language, 'phone')}: <bdi dir="ltr">{presentation.contact.phone}</bdi></div>}{presentation.contact.websiteVisible && presentation.contact.website && <div>{documentLabel(model.identity.language, 'website')}: <bdi dir="ltr">{presentation.contact.website}</bdi></div>}{presentation.contact.emailVisible && presentation.contact.email && <div>{documentLabel(model.identity.language, 'email')}: <bdi dir="ltr">{presentation.contact.email}</bdi></div>}</section>
}

function SellerBrand({ model }: { model: DocumentViewModel }) {
  const { seller, presentation } = model
  const logo = presentation.logo.previewUrl ?? presentation.logo.assetPath
  return <section className="a4-seller a4-seller--brand">
    {presentation.logo.visible && logo && <img className={`a4-logo a4-logo--${presentation.logo.size ?? 'medium'}`} src={logo} alt="" onError={event => { event.currentTarget.style.display = 'none' }} />}
    {seller.displayHeading && <div className="a4-display-heading" dir="auto">{seller.displayHeading}</div>}
    {seller.displaySubheading && <div className="a4-display-subheading" dir="auto">{seller.displaySubheading}</div>}
    {!seller.displayHeading && names(model, seller.registeredName, seller.registeredNameAr).map((value, index) => <div className="a4-registered-name" key={`${value}-${index}`} dir="auto">{value}</div>)}
  </section>
}

function Buyer({ model }: { model: DocumentViewModel }) { const { buyer } = model; return <section className="a4-buyer"><div className="a4-section-title">{documentLabel(model.identity.language, 'billTo')}</div>{names(model, buyer.name, buyer.nameAr).map((value, index) => <div className="a4-buyer-name" key={`${value}-${index}`} dir="auto">{value}</div>)}{names(model, buyer.address, buyer.addressAr).map((value, index) => <div key={`${value}-${index}`} dir="auto">{value}</div>)}{buyer.vatNumber && <div>{documentLabel(model.identity.language, 'customerVatNumber')}: <bdi dir="ltr">{buyer.vatNumber}</bdi></div>}{buyer.identifierValue && <div>{buyer.identifierType ?? documentLabel(model.identity.language, 'identifier')}: <bdi dir="ltr">{buyer.identifierValue}</bdi></div>}</section> }

function ItemTable({ model }: { model: DocumentViewModel }) { const credit = model.identity.kind === 'credit_note'; const hasDiscount = model.items.some(item => item.discount > 0.005); return <table className="a4-items"><thead><tr><th>#</th><th>{documentLabel(model.identity.language, 'description')}</th><th>{documentLabel(model.identity.language, 'quantity')}</th><th>{documentLabel(model.identity.language, 'unitPrice')}</th>{hasDiscount && <th>{documentLabel(model.identity.language, 'discount')}</th>}<th>{documentLabel(model.identity.language, 'taxableAmount')}</th><th>{documentLabel(model.identity.language, 'vatAmount')}</th><th>{documentLabel(model.identity.language, 'totalIncludingVat')}</th></tr></thead><tbody>{model.items.map((item, index) => <tr key={`${item.description}-${index}`}><td>{index + 1}</td><td>{names(model, item.description, item.descriptionAr).map((value, nameIndex) => <div key={`${value}-${nameIndex}`} dir="auto">{value}</div>)}</td><td><QuantityCell model={model} item={item} quantity={credit && item.creditedQuantity != null ? item.creditedQuantity : item.quantity} /></td><td><Money value={item.unitPrice} model={model} /></td>{hasDiscount && <td>{item.discount > 0.005 ? <Money value={item.discount} model={model} /> : '—'}</td>}<td><Money value={item.taxableAmount} model={model} /></td><td><span><bdi dir="ltr">{formatDocumentQuantity(item.vatRate, model)}%</bdi> · <Money value={item.vatAmount} model={model} /></span></td><td><Money value={item.lineTotal} model={model} /></td></tr>)}</tbody></table> }

function Totals({ model }: { model: DocumentViewModel }) { return <section className="a4-totals">{buildVisibleTotals(model).map(row => <div className={row.emphasized ? 'a4-totals__grand' : undefined} key={row.key}><span>{row.label}</span><Money value={row.value} model={model} /></div>)}</section> }

function Payment({ model }: { model: DocumentViewModel }) { const credit = model.identity.kind === 'credit_note'; return <section className="a4-payment"><div className="a4-section-title">{documentLabel(model.identity.language, credit ? 'refundIssued' : 'paymentMethod')}</div>{model.payments.length > 0 ? model.payments.map((payment, index) => <div key={`${payment.method}-${index}`}><span>{documentPaymentLabel(model.identity.language, payment.method)}</span><Money value={payment.amount} model={model} />{payment.method === 'cash' && payment.cashTendered != null && Math.abs(payment.cashTendered - model.totals.total) > 0.005 && <span>{documentLabel(model.identity.language, 'received')}: <Money value={payment.cashTendered} model={model} /></span>}{payment.method === 'cash' && model.presentation.thermal.showCashChange && (payment.change ?? 0) > 0 && <span>{documentLabel(model.identity.language, 'change')}: <Money value={payment.change ?? 0} model={model} /></span>}</div>) : <div><span>{documentPaymentLabel(model.identity.language, 'other')}</span></div>}</section> }

function QrVerification({ model, options }: { model: DocumentViewModel; options: A4RenderOptions }) { if (options.nonFiscalDemo) return null; return <section className="a4-qr">{options.qrImageUrl ? <img src={options.qrImageUrl} alt={documentLabel(model.identity.language, 'qrCode')} /> : <div className="a4-qr-placeholder">{documentLabel(model.identity.language, 'qrCode')}</div>}{documentLabelLines(model.identity.language, 'scanToVerify').map((line, index) => <div key={`${line}-${index}`} dir="auto">{line}</div>)}</section> }
function Footer({ model, options }: { model: DocumentViewModel; options: A4RenderOptions }) { const footer = [model.presentation.footer.thankYouVisible ? model.presentation.footer.thankYou : null, model.presentation.footer.footerVisible ? model.presentation.footer.footer : null, model.presentation.footer.refundVisible ? model.presentation.footer.refund : null].filter(Boolean); return <footer className="a4-footer">{footer.length > 0 && <><div className="a4-footer-divider" aria-hidden="true" /><div className={`a4-footer-copy ${model.presentation.footer.bold || footer.length > 0 ? 'font-bold' : ''}`}>{footer.map((line, index) => <div key={`${line}-${index}`} dir="auto">{line}</div>)}</div></>}{options.pageNumbers && <span className="a4-page-number" />}</footer> }
function DocumentTitle({ model, options }: { model: DocumentViewModel; options: A4RenderOptions }) { const credit = model.identity.kind === 'credit_note'; const debit = model.identity.kind === 'debit_note'; const key = credit ? (model.identity.invoiceType === 'standard' ? 'taxCreditNote' : 'simplifiedTaxCreditNote') : debit ? (model.identity.invoiceType === 'standard' ? 'taxDebitNote' : 'simplifiedTaxDebitNote') : (model.identity.invoiceType === 'standard' ? 'standardTaxInvoice' : 'simplifiedTaxInvoice'); const lines = options.nonFiscalDemo ? ['DEMO — NOT A TAX INVOICE', 'تجريبي — ليست فاتورة ضريبية'] : documentLabelLines(model.identity.language, key); return <section className="a4-document-title">{lines.map((line, index) => <div key={`${line}-${index}`} className={index === 0 ? 'a4-document-title__main' : 'a4-document-title__sub'} dir="auto">{line}</div>)}</section> }
function Adjustment({ model }: { model: DocumentViewModel }) { const credit = model.identity.kind === 'credit_note'; const debit = model.identity.kind === 'debit_note'; if (!credit && !debit) return null; return <section className={`a4-credit ${debit ? 'a4-debit' : ''}`}><strong>{documentLabel(model.identity.language, debit ? 'debitNoteReference' : 'creditNoteReference')}</strong>{model.compliance.originalDocument.number && <span>{documentLabel(model.identity.language, 'originalInvoice')}: <bdi dir="ltr">{model.compliance.originalDocument.number}</bdi></span>}{model.compliance.creditReason && <span>{documentLabel(model.identity.language, 'reason')}: <span dir="auto">{model.compliance.creditReason}</span></span>}</section> }
function Shell({ template, model, options, children }: { template: string; model: DocumentViewModel; options: A4RenderOptions; children: ReactNode }) {
  const artwork = model.template.headerAssetEnabled ? resolveInvoiceLogoUrl(model.template.headerAssetPath) : null
  return <article
    className={`a4-document a4-document--${template} a4-header--${resolveA4Template(model).headerStyle}`}
    dir={model.identity.direction}
    lang={model.identity.language === 'both' ? undefined : model.identity.language}
    style={{ '--a4-accent': model.template.accentColor, '--a4-on-accent': contrastForeground(model.template.accentColor), '--a4-header-height': `${model.template.headerAssetHeight}mm`, '--a4-header-spacing': `${model.template.headerAssetSpacing}mm` } as CSSProperties}
  >{options.sampleLabel && <div className="a4-sample">{options.sampleLabel}</div>}{artwork && <div className="a4-header-artwork"><img src={artwork} alt="" style={{ objectFit: model.template.headerAssetFit }} onError={event => { event.currentTarget.parentElement!.style.display = 'none' }} /></div>}{children}</article>
}

function contrastForeground(hex: string) {
  const value = hex.replace('#', '')
  const [r, g, b] = [0, 2, 4].map(index => Number.parseInt(value.slice(index, index + 2), 16) / 255)
  const luminance = [r, g, b].map(channel => channel <= .03928 ? channel / 12.92 : ((channel + .055) / 1.055) ** 2.4).reduce((sum, channel, index) => sum + channel * [.2126, .7152, .0722][index], 0)
  const whiteContrast = 1.05 / (luminance + .05)
  return whiteContrast >= 4.5 ? '#ffffff' : '#111827'
}

function ClassicV1({ model, options }: { model: DocumentViewModel; options: A4RenderOptions }) { return <Shell template="classic" model={model} options={options}><header className="a4-classic-head"><Seller model={model} /><div><DocumentTitle model={model} options={options} /><DateMeta model={model} /></div></header><Buyer model={model} /><Adjustment model={model} /><ItemTable model={model} /><div className="a4-classic-summary"><QrVerification model={model} options={options} /><Payment model={model} /><Totals model={model} /></div><Footer model={model} options={options} /></Shell> }
function ModernSplitV1({ model, options }: { model: DocumentViewModel; options: A4RenderOptions }) { return <Shell template="modern_split" model={model} options={options}><div className="a4-split-shell"><aside className="a4-split-rail"><Seller model={model} /><DocumentTitle model={model} options={options} /><DateMeta model={model} /><QrVerification model={model} options={options} /></aside><main className="a4-split-body"><Buyer model={model} /><Adjustment model={model} /><ItemTable model={model} /><Totals model={model} /><Payment model={model} /><Footer model={model} options={options} /></main></div></Shell> }
function MinimalProfessionalV1({ model, options }: { model: DocumentViewModel; options: A4RenderOptions }) { return <Shell template="minimal_professional" model={model} options={options}><header className="a4-minimal-head"><Seller model={model} /><DocumentTitle model={model} options={options} /></header><div className="a4-minimal-parties"><Buyer model={model} /><DateMeta model={model} /></div><Adjustment model={model} /><ItemTable model={model} /><div className="a4-minimal-total"><Totals model={model} /></div><div className="a4-minimal-foot"><DateMeta model={model} /><QrVerification model={model} options={options} /><Payment model={model} /></div><Footer model={model} options={options} /></Shell> }
function ExecutiveGreenV1({ model, options }: { model: DocumentViewModel; options: A4RenderOptions }) { return <Shell template="executive_green" model={model} options={options}><header className="a4-executive-band"><SellerBrand model={model} /><DocumentTitle model={model} options={options} /></header><section className="a4-executive-summary"><QrVerification model={model} options={options} /><DateMeta model={model} /><div className="a4-executive-grand"><span>{documentLabel(model.identity.language, 'totalIncludingVat')}</span><Money value={model.totals.total} model={model} /></div></section><div className="a4-executive-parties"><Seller model={model} /><Buyer model={model} /></div><Adjustment model={model} /><ItemTable model={model} /><div className="a4-executive-lower"><Totals model={model} /><Payment model={model} /></div><Footer model={model} options={options} /></Shell> }
function CleanLedgerV1({ model, options }: { model: DocumentViewModel; options: A4RenderOptions }) { return <Shell template="clean_ledger" model={model} options={options}><header className="a4-ledger-head"><DocumentTitle model={model} options={options} /><DateMeta model={model} /></header><div className="a4-ledger-parties"><Seller model={model} /><Buyer model={model} /></div><Adjustment model={model} /><ItemTable model={model} /><div className="a4-ledger-summary"><Payment model={model} /><Totals model={model} /></div><div className="a4-ledger-verification"><QrVerification model={model} options={options} /><DateMeta model={model} /><Footer model={model} options={options} /></div></Shell> }
function ContemporaryBorderV1({ model, options }: { model: DocumentViewModel; options: A4RenderOptions }) { return <Shell template="contemporary_border" model={model} options={options}><header className="a4-frame-title"><DocumentTitle model={model} options={options} /></header><div className="a4-frame-cards"><Seller model={model} /><Buyer model={model} /><DateMeta model={model} /></div><Adjustment model={model} /><section className="a4-frame-table"><ItemTable model={model} /></section><div className="a4-frame-bottom"><section><Totals model={model} /></section><section><QrVerification model={model} options={options} /><Payment model={model} /></section></div><Footer model={model} options={options} /></Shell> }

export default function A4Document({ model, options = {} }: A4DocumentProps) { const resolved = resolveA4Template(model); const Template = resolved.renderer === 'modern_split_v1' ? ModernSplitV1 : resolved.renderer === 'minimal_professional_v1' ? MinimalProfessionalV1 : resolved.renderer === 'executive_green_v1' ? ExecutiveGreenV1 : resolved.renderer === 'clean_ledger_v1' ? CleanLedgerV1 : resolved.renderer === 'contemporary_border_v1' ? ContemporaryBorderV1 : ClassicV1; const target = options.pdfMode ? 'pdf' : options.preview ? 'preview' : 'print'; return <div id={options.id ?? 'a4-document'} className={`a4-document-frame ${options.preview ? '' : 'a4-document-frame--print-only'}`} data-render-target={target} data-template-requested={`${resolved.requestedId}@${resolved.requestedVersion}`} data-template-resolved={`${resolved.resolvedId}@${resolved.resolvedVersion}`} style={{ fontFamily: documentFontFamily(model.identity.language) }}><Template model={model} options={options} /></div> }
