import { formatDocumentMoney, formatDocumentQuantity, type DocumentViewModel } from '@/lib/invoices/documentViewModel'

export default function DocumentPreview({ model, mode, logoSrc, copy }: { model: DocumentViewModel; mode: 'thermal' | 'a4'; logoSrc: string | null; copy: Record<string, string> }) {
  const { seller, presentation, items, totals } = model
  const width = mode === 'thermal' ? (presentation.thermal.width === '58mm' ? 'max-w-[250px]' : 'max-w-[330px]') : 'max-w-[620px]'
  const visibleFooter = [presentation.footer.thankYouVisible ? presentation.footer.thankYou : null, presentation.footer.footerVisible ? presentation.footer.footer : null, presentation.footer.refundVisible ? presentation.footer.refund : null].filter(Boolean)
  return <div className={`mx-auto ${width} bg-white text-gray-900 shadow-[0_18px_50px_rgba(15,36,25,0.12)] ring-1 ring-gray-200`} dir={model.identity.direction}>
    <div className={`${mode === 'thermal' ? presentation.thermal.density === 'compact' ? 'p-4' : 'p-5' : 'p-7'} border-b border-dashed border-gray-200`}>
      <div className="flex items-start justify-between gap-4"><div className="min-w-0">{presentation.logo.visible && logoSrc && <img src={logoSrc} alt="" className={`${presentation.logo.size === 'small' ? 'h-8' : presentation.logo.size === 'large' ? 'h-16' : 'h-11'} mb-3 max-w-32 object-contain`} />}{seller.displayHeading && <p className="text-base font-black text-[#0F2419]">{seller.displayHeading}</p>}{seller.displaySubheading && <p className="mt-0.5 text-[10px] text-gray-500">{seller.displaySubheading}</p>}{seller.company.visible && <p className="mt-1 text-xs font-semibold" dir="auto">{seller.renderName}</p>}{seller.branch.visible && seller.branch.name && <p className="mt-1 text-[10px] text-gray-500" dir="auto">{seller.branch.name}</p>}</div><div className="text-end"><p className="text-xs font-bold">{copy.invoiceTitle}</p><p className="mt-1 font-mono text-[10px] text-gray-500" dir="ltr">{model.identity.number}</p></div></div>
      <div className="mt-3 space-y-0.5 text-[9px] text-gray-500">{presentation.contact.phoneVisible && presentation.contact.phone && <p dir="ltr">{presentation.contact.phone}</p>}{presentation.contact.emailVisible && presentation.contact.email && <p dir="ltr">{presentation.contact.email}</p>}{presentation.contact.websiteVisible && presentation.contact.website && <p dir="ltr">{presentation.contact.website}</p>}{presentation.contact.addressVisible && seller.registeredAddress && <p dir="auto">{seller.registeredAddress}</p>}</div>
    </div>
    <div className={mode === 'thermal' ? 'p-4' : 'p-7'}><div className="grid grid-cols-[1fr_auto_auto] gap-2 border-b border-gray-200 pb-2 text-[9px] font-semibold text-gray-500"><span>{copy.item}</span><span>{copy.quantity}</span><span>{copy.total}</span></div>{items.map(item => <div key={`${item.description}-${item.quantity}`} className="grid grid-cols-[1fr_auto_auto] gap-2 border-b border-gray-100 py-2 text-[10px]"><span className={presentation.thermal.wrapItemNames ? '' : 'truncate'} dir="auto">{model.identity.language === 'ar' ? item.descriptionAr || item.description : model.identity.language === 'both' ? `${item.description} / ${item.descriptionAr || item.description}` : item.description}</span><span dir="ltr">{formatDocumentQuantity(item.quantity, model)}</span><span dir="ltr">SAR {formatDocumentMoney(item.lineTotal, model)}</span></div>)}<div className="ms-auto mt-4 w-44 space-y-1 text-[10px]"><div className="flex justify-between"><span>{copy.subtotal}</span><span dir="ltr">SAR {formatDocumentMoney(totals.subtotal, model)}</span></div>{totals.discount > 0 && <div className="flex justify-between"><span>{copy.discount ?? 'Discount'}</span><span dir="ltr">SAR {formatDocumentMoney(totals.discount, model)}</span></div>}<div className="flex justify-between"><span>{copy.vat}</span><span dir="ltr">SAR {formatDocumentMoney(totals.vat, model)}</span></div><div className="flex justify-between border-t pt-1 text-xs font-bold"><span>{copy.total}</span><span dir="ltr">SAR {formatDocumentMoney(totals.total, model)}</span></div></div>
      <div className="mt-5 flex items-end justify-between gap-4"><div className="space-y-1 text-[9px] text-gray-500">{visibleFooter.map(note => <p key={note}>{note}</p>)}</div><div aria-label={copy.qr} className={`${presentation.thermal.qrSize === 'small' ? 'h-10 w-10' : presentation.thermal.qrSize === 'large' ? 'h-16 w-16' : 'h-12 w-12'} grid place-items-center bg-gray-100 text-[7px] text-gray-400`}>{copy.qr}</div></div>
    </div>
  </div>
}
