import { useEffect,useMemo,useState } from 'react'
import { AlertTriangle,Loader2,ShieldCheck } from 'lucide-react'
import { useTranslation } from 'react-i18next'
import { supabase } from '@/lib/supabase'
import { useAuth } from '@/hooks/useAuth'
import { activateCompliance,complianceCapability,getComplianceAudit,getComplianceReadiness,recoverLegacyMode,reviewCompliance,saveComplianceDraft,submitComplianceReview } from '@/lib/complianceIdentity'
import type { BranchComplianceProfile,ComplianceAuditItem,ComplianceReadiness,DraftProfilePayload } from '@/types/complianceIdentity'

const EMPTY:DraftProfilePayload={registeredSellerName:'',registeredSellerNameAr:'',vatNumber:'',registrationScheme:'CRN',registrationIdentifier:'',buildingNumber:'',street:'',district:'',city:'',postalCode:'',country:'SA',evidenceReference:''}
const fromProfile=(p:BranchComplianceProfile|null):DraftProfilePayload=>p?{registeredSellerName:p.registeredSellerName??'',registeredSellerNameAr:p.registeredSellerNameAr??'',vatNumber:p.vatNumber??'',registrationScheme:p.registrationScheme,registrationIdentifier:p.registrationIdentifier??'',buildingNumber:p.buildingNumber??'',street:p.street??'',district:p.district??'',city:p.city??'',postalCode:p.postalCode??'',country:p.country,evidenceReference:p.evidenceReference??''}:EMPTY

export default function OfficialSellerProfilePage(){
 const {t}=useTranslation('settings');const {profile}=useAuth();const owner=profile?.role==='owner';const [enabled,setEnabled]=useState<boolean|null>(null);const [branches,setBranches]=useState<{id:string;name:string}[]>([]);const [branchId,setBranchId]=useState('');const [ready,setReady]=useState<ComplianceReadiness|null>(null);const [form,setForm]=useState<DraftProfilePayload>(EMPTY);const [reason,setReason]=useState('');const [audit,setAudit]=useState<ComplianceAuditItem[]>([]);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [confirm,setConfirm]=useState(false)
 const complete=useMemo(()=>!!form.registeredSellerName.trim()&&/^3\d{13}3$/.test(form.vatNumber)&&!!form.registrationIdentifier.trim()&&!!form.buildingNumber.trim()&&!!form.street.trim()&&!!form.district.trim()&&!!form.city.trim()&&/^\d{5}$/.test(form.postalCode),[form])
 async function load(id=branchId){if(!id)return;const [r,a]=await Promise.all([getComplianceReadiness(id),getComplianceAudit(id)]);setReady(r);setForm(fromProfile(r.profile));setAudit(a??[])}
 useEffect(()=>{let stop=false;(async()=>{try{const c=await complianceCapability();if(stop)return;setEnabled(c.available);if(!c.available)return;const {data}=await supabase.from('branches').select('id,name').order('name');const rows=(data??[]) as {id:string;name:string}[];setBranches(rows);if(rows[0])setBranchId(rows[0].id)}catch(e:any){setError(e.message)}})();return()=>{stop=true}},[])
 useEffect(()=>{if(enabled&&branchId)load(branchId).catch(e=>setError(e.message))},[enabled,branchId])
 const set=(k:keyof DraftProfilePayload)=>(e:React.ChangeEvent<HTMLInputElement|HTMLSelectElement>)=>setForm(v=>({...v,[k]:e.target.value}))
 async function act(fn:()=>Promise<unknown>){setBusy(true);setError('');try{await fn();await load();setReason('');setConfirm(false)}catch(e:any){console.error('[OfficialSellerProfile]',e);setError(t('officialSeller.actionFailed'))}finally{setBusy(false)}}
 if(enabled===null)return <Loader2 className="animate-spin"/>
 if(!enabled)return <div className="card p-6"><h1 className="text-lg font-bold">{t('officialSeller.title')}</h1><p className="mt-2 text-sm text-gray-500">{t('officialSeller.notEnabled')}</p></div>
 return <div className="max-w-5xl space-y-5"><div><h1 className="text-2xl font-bold text-gray-950">{t('officialSeller.title')}</h1><p className="mt-1 text-sm text-gray-500">{t('officialSeller.subtitle')}</p></div>
 <div className="card p-4"><label className="label">{t('officialSeller.branch')}</label><select className="input" value={branchId} onChange={e=>setBranchId(e.target.value)}>{branches.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select><div className="mt-3 flex gap-2 text-xs"><span className="rounded-full bg-gray-100 px-2 py-1">{t(`officialSeller.status.${ready?.status??'missing'}`)}</span><span className="rounded-full bg-gray-100 px-2 py-1">{t(`officialSeller.mode.${ready?.mode??'legacy'}`)}</span></div></div>
 <div className="rounded-xl bg-amber-50 p-4 text-xs text-amber-900"><AlertTriangle size={16} className="mb-2"/>{t('officialSeller.credentialWarning')}</div>
 <div className="card p-5 grid gap-4 md:grid-cols-2">{(['registeredSellerName','registeredSellerNameAr','vatNumber','registrationIdentifier','buildingNumber','street','district','city','postalCode','country','evidenceReference'] as const).map(k=><div key={k} className={k==='evidenceReference'?'md:col-span-2':''}><label className="label">{t(`officialSeller.fields.${k}`)}</label><input className="input" dir={k==='vatNumber'||k==='registrationIdentifier'||k==='buildingNumber'||k==='postalCode'?'ltr':'auto'} value={form[k]} onChange={set(k)} disabled={!owner}/></div>)}<div><label className="label">{t('officialSeller.fields.registrationScheme')}</label><select className="input" dir="ltr" value={form.registrationScheme} onChange={set('registrationScheme')} disabled={!owner}>{['CRN','MOM','MLS','SAG','OTH'].map(x=><option key={x}>{x}</option>)}</select></div><div className="md:col-span-2"><label className="label">{t('officialSeller.reason')}</label><input className="input" value={reason} onChange={e=>setReason(e.target.value)} disabled={!owner}/></div>{error&&<p className="md:col-span-2 text-xs text-red-600">{error}</p>}</div>
 {owner&&<div className="card p-4 space-y-3"><div className="flex flex-wrap gap-2"><button className="btn-secondary" disabled={busy} onClick={()=>act(()=>saveComplianceDraft(branchId,form,reason))}>{t('officialSeller.actions.saveDraft')}</button><button className="btn-primary" disabled={busy||!complete||!reason.trim()} onClick={()=>act(()=>submitComplianceReview(branchId,reason))}>{t('officialSeller.actions.submit')}</button>{ready?.status==='needs_review'&&<><button className="btn-primary" disabled={!confirm||!reason.trim()} onClick={()=>act(()=>reviewCompliance({branchId,decision:'verify',reason,confirmation:true}))}>{t('officialSeller.actions.verify')}</button><button className="btn-secondary" disabled={!confirm||!reason.trim()} onClick={()=>act(()=>reviewCompliance({branchId,decision:'reject',reason,confirmation:true}))}>{t('officialSeller.actions.reject')}</button></>}</div><label className="flex gap-2 text-xs"><input type="checkbox" checked={confirm} onChange={e=>setConfirm(e.target.checked)}/>{t('officialSeller.strongConfirmation')}</label>{ready?.status==='verified'&&ready.mode==='legacy'&&<button className="btn-primary" disabled={!confirm||!reason.trim()} onClick={()=>act(()=>activateCompliance({branchId,reason}))}><ShieldCheck size={14}/>{t('officialSeller.actions.activate')}</button>}{ready?.mode==='protected'&&<button className="rounded-xl bg-red-600 px-4 py-2 text-xs font-semibold text-white" disabled={!confirm||!reason.trim()} onClick={()=>act(()=>recoverLegacyMode({branchId,reason,confirmation:true}))}>{t('officialSeller.actions.recover')}</button>}</div>}
 <div className="card p-5"><h2 className="text-sm font-bold">{t('officialSeller.history')}</h2><div className="mt-3 space-y-2">{audit.length?audit.map(a=><div key={a.id} className="rounded-xl bg-gray-50 p-3 text-xs"><p className="font-semibold">{a.action}</p><p className="text-gray-500">{new Date(a.created_at).toLocaleString()} · {a.actor_role??'—'}</p><p className="mt-1 text-gray-600">{String(a.metadata?.reason??'')}</p></div>):<p className="text-xs text-gray-400">{t('officialSeller.noHistory')}</p>}</div></div></div>
}
